name: Test_bypass

on: [push,pull_request]

permissions:
  pull-requests: write
  contents: write

jobs:
  deploy_to_git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get app token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      # https://github.com/tibdex/github-app-token/issues/54#issuecomment-1410471261
        env:
          OPENSSL_CONF: /dev/null
      - name: test
        run: |
          touch hello.txt
      - name: Create commit
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "auto generate shared library"
      - name: Create pull request
        id: cpr 
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}
          signoff: true
          branch: ${{ github.head_ref }}_11111
          base: test
          delete-branch: true
          title: 'test_bypass'
          body: test
          labels: automerge
          draft: false
      # don't need to trigger other actions
      - name: Enable Pull Request Automerge
        run: gh pr merge --auto --squash -d ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}